server:
    url: http://localhost:1337
    title: Agora
mysql:
    cnct: true
    host: 127.0.0.1
    port: 3306
    user: root
    pssw: pssw2204
    dbts: agora
    socketPath: /Applications/MAMP/tmp/mysql/mysql.sock
port:
    local   : 1337
    public  : 8080
links:
    assets:
        private : /public/assets/
        public  : /assets/
    views: /views/